// داده‌ی نمونه‌ی تیکت‌های پشتیبانی — تیکت‌هایی از کاربران لایه‌های مختلف سازمان به تیم سازنده.
import { DAY_BASE, vendorTeam, type ActorKind, type CapturedContext, type EventKind, type Ticket, type TicketEvent, type TicketStatus } from "./model";

// «امروز ساعت ۰۸:۳۰» در تقویم دمو؛ رویدادهای نمونه نسبت به آن ساخته می‌شوند
const B = DAY_BASE + 8 * 60 + 30;
const ago = (hours: number) => Math.round(B - hours * 60);
const [V1, V2, V3, V4] = vendorTeam.map((v) => v.name);

let evSeq = 0;
const ev = (hoursAgo: number, kind: EventKind, actor: string, actorKind: ActorKind, rest: Partial<TicketEvent> = {}): TicketEvent => ({
  id: `se${++evSeq}`,
  at: ago(hoursAgo),
  kind,
  actor,
  actorKind,
  ...rest,
});
const st = (hoursAgo: number, from: TicketStatus, to: TicketStatus, actor: string, actorKind: ActorKind = "vendor", text?: string) => ev(hoursAgo, "status", actor, actorKind, { from, to, text });
const ctx = (route: string, pageTitle: string, scope: string, roles: string, hoursAgo: number, ua = "Chrome 128 · Windows", screen = "۱۴۴۰×۷۸۰ (صفحه‌نمایش ۱۹۲۰×۱۰۸۰)", appVersion = "۳.۸.۲"): CapturedContext => ({
  route,
  pageTitle,
  userAgent: ua,
  screen,
  scope,
  roles,
  appVersion,
  at: ago(hoursAgo),
});

type Base = Omit<Ticket, "createdAt" | "updatedAt" | "events" | "labels" | "links" | "attachments"> & Partial<Pick<Ticket, "labels" | "links" | "attachments">>;
function mk(t: Base, createdHoursAgo: number, events: TicketEvent[]): Ticket {
  const created = ev(createdHoursAgo, "created", t.reporterName, "reporter");
  const all = [created, ...events].sort((a, b) => a.at - b.at);
  return { labels: [], links: [], attachments: [], ...t, createdAt: created.at, updatedAt: all[all.length - 1].at, events: all };
}

export function seedTickets(): Ticket[] {
  evSeq = 0;
  return [
    mk(
      {
        id: "MSH-1024",
        title: "خطای ۴۱۳ هنگام بارگذاری فایل بزرگ‌تر از ۵۰ مگابایت در مخزن دانش",
        description: "گزارش ارزیابی اعتباری ۸۰ مگابایتی را در مخزن دانش بارگذاری می‌کنم و پس از چند ثانیه خطای ۴۱۳ نمایش داده می‌شود.",
        type: "خطا",
        module: "مدیریت دانش",
        priority: "زیاد",
        severity: "شدید",
        status: "in-progress",
        reporterId: "u13",
        reporterName: "مهندس بردیا کوشا",
        reporterScopeId: "u-bank-credit",
        assigneeId: "v3",
        firstResponseAt: ago(25),
        steps: "۱. مدیریت دانش ← مخزن دانش ← سند جدید\n۲. انتخاب فایل PDF با حجم ۸۰ مگابایت\n۳. ذخیره",
        expected: "فایل بارگذاری و سند ثبت شود.",
        actual: "پیام «Request Entity Too Large (413)» و ثبت نشدن سند.",
        labels: ["بارگذاری", "زیرساخت"],
        attachments: [{ name: "screenshot-413.png", size: 284000, at: ago(26), by: "مهندس بردیا کوشا" }],
        context: ctx("/dashboard/knowledge?tab=bank", "مدیریت دانش", "بنیاد مستضعفان › هلدینگ مالی و سرمایه‌گذاری سینا › بانک سینا › واحد اعتبارسنجی", "مدیر شرکت، کارشناس اعتبارسنجی", 26),
      },
      26,
      [
        ev(25.2, "assign", V1, "vendor", { to: V3 }),
        st(25, "new", "triage", V1, "vendor", "بررسی شد؛ احتمالاً محدودیت حجم درخواست در سرور است."),
        ev(24.9, "comment", V3, "vendor", { text: "سلام، مشکل بازتولید شد. محدودیت فعلی بارگذاری ۵۰ مگابایت است و در حال افزایش آن هستیم." }),
        ev(24.5, "note", V3, "vendor", { internal: true, text: "client_max_body_size در nginx روی 50M است؛ باید 200M شود و timeout آپلود هم بالا برود. نیاز به هماهنگی با تیم زیرساخت مشتری." }),
        st(3, "triage", "in-progress", V3),
      ],
    ),
    mk(
      {
        id: "MSH-1025",
        title: "امکان خروجی Excel از گزارش کارکرد ماهانه",
        description: "برای ارسال کارکرد ماهانه به واحد مالی نیاز داریم گزارش را به‌صورت فایل Excel دریافت کنیم؛ الان فقط چاپ دارد.",
        type: "درخواست قابلیت",
        module: "گزارش فعالیت و زمان کاری",
        priority: "متوسط",
        severity: "متوسط",
        status: "triage",
        reporterId: "u12",
        reporterName: "دکتر یاسمن روشن",
        reporterScopeId: "c-pak",
        assigneeId: "v1",
        firstResponseAt: ago(44),
        labels: ["گزارش", "خروجی"],
        context: ctx("/dashboard/activity", "گزارش فعالیت‌های من", "بنیاد مستضعفان › هلدینگ صنایع غذایی سینا › لبنیات پاک", "کاربر عادی، کارشناس مالی هلدینگ", 46, "Firefox 130 · Windows"),
      },
      46,
      [
        ev(44, "assign", V1, "vendor", { to: V1 }),
        st(44, "new", "triage", V1, "vendor"),
        ev(43.8, "comment", V1, "vendor", { text: "از پیشنهاد شما سپاسگزاریم؛ این مورد در نقشه‌ی راه نسخه‌ی ۳.۹.۰ قرار گرفت." }),
        ev(43.5, "labels", V1, "vendor", { to: "گزارش، خروجی" }),
      ],
    ),
    mk(
      {
        id: "MSH-1026",
        title: "دکمه‌ی «تخصیص نقش» برای مدیر شرکت غیرفعال است",
        description: "به‌عنوان مدیر شرکت بانک سینا می‌خواهم نقش «کارشناس اعتبارسنجی» را به همکار جدید بدهم ولی دکمه غیرفعال است.",
        type: "مشکل دسترسی",
        module: "نقش و دسترسی",
        priority: "زیاد",
        severity: "شدید",
        status: "need-info",
        reporterId: "u13",
        reporterName: "مهندس بردیا کوشا",
        reporterScopeId: "c-bank-sina",
        assigneeId: "v1",
        firstResponseAt: ago(5.5),
        labels: ["دسترسی"],
        context: ctx("/dashboard/settings?section=roles", "تنظیمات سامانه", "بنیاد مستضعفان › هلدینگ مالی و سرمایه‌گذاری سینا › بانک سینا", "مدیر شرکت", 6),
      },
      6,
      [
        st(5.5, "new", "triage", V1),
        ev(5.5, "assign", V1, "vendor", { to: V1 }),
        st(5, "triage", "need-info", V1, "vendor"),
        ev(5, "comment", V1, "vendor", { text: "لطفاً بفرمایید هنگام تخصیص در کدام واحد ایستاده بودید (سوییچر «تغییر سازمان یا نقش») و همکار جدید عضو کدام واحد است؟ تخصیص فقط برای اعضای همان واحد یا زیرمجموعه‌اش فعال است." }),
      ],
    ),
    mk(
      {
        id: "MSH-1027",
        title: "کندی شدید بارگذاری بُرد پروژه با بیش از ۳۰۰ تسک",
        description: "بُرد پروژه‌ی نوسازی توربین‌ها حدود ۲۰ ثانیه طول می‌کشد تا باز شود و جابه‌جایی کارت‌ها گیر می‌کند. کل تیم بهره‌برداری معطل است.",
        type: "کندی و کارایی",
        module: "مدیریت پروژه",
        priority: "بحرانی",
        severity: "مسدودکننده",
        status: "new",
        reporterId: "u5",
        reporterName: "محسن مردعلی",
        reporterScopeId: "c-saba-niru",
        steps: "باز کردن پروژه‌ی «نوسازی توربین‌های واحد ۲» ← زبانه‌ی بُرد",
        expected: "بُرد در کمتر از ۲ ثانیه باز شود.",
        actual: "حدود ۲۰ ثانیه صفحه سفید می‌ماند.",
        labels: ["کارایی"],
        attachments: [{ name: "performance-trace.json", size: 1830000, at: ago(0.6), by: "محسن مردعلی" }],
        context: ctx("/dashboard/projects/p-saba-2?tab=board", "پروژه‌های من", "بنیاد مستضعفان › هلدینگ برق و انرژی صبا › نیروگاه‌های صبا", "مدیر پروژه، کاربر عادی", 0.7, "Edge 128 · Windows"),
      },
      0.7,
      [ev(0.6, "attachment", "محسن مردعلی", "reporter", { files: ["performance-trace.json"] })],
    ),
    mk(
      {
        id: "MSH-1028",
        title: "تقویم جلسات در حالت تاریک خوانا نیست",
        description: "در حالت تاریک عنوان جلسه‌ها روی پس‌زمینه‌ی تیره تقریباً دیده نمی‌شود.",
        type: "خطا",
        module: "تقویم",
        priority: "کم",
        severity: "جزئی",
        status: "resolved",
        reporterId: "u6",
        reporterName: "دکتر آرین صدرا",
        reporterScopeId: "u-behnoush-prod",
        assigneeId: "v2",
        firstResponseAt: ago(70),
        resolvedAt: ago(4),
        fixedIn: "۳.۸.۲",
        labels: ["حالت تاریک", "ظاهر"],
        attachments: [{ name: "calendar-dark.png", size: 412000, at: ago(72), by: "دکتر آرین صدرا" }],
        context: ctx("/dashboard/events?view=calendar", "رویداد و جلسات", "بنیاد مستضعفان › هلدینگ صنایع غذایی سینا › بهنوش ایران › معاونت تولید", "کاربر عادی، سرپرست تولید", 72, "Safari 17 · macOS", "۱۲۸۰×۷۲۰ (صفحه‌نمایش ۱۴۴۰×۹۰۰)"),
      },
      72,
      [
        st(70, "new", "triage", V4),
        ev(70, "comment", V4, "vendor", { text: "بازتولید شد؛ رنگ متن عنوان در حالت تاریک از توکن رنگ پیروی نمی‌کند." }),
        ev(69, "assign", V1, "vendor", { to: V2 }),
        st(30, "triage", "in-progress", V2),
        ev(4.2, "release", V2, "vendor", { to: "۳.۸.۲" }),
        st(4, "in-progress", "resolved", V2, "vendor"),
        ev(4, "comment", V2, "vendor", { text: "مشکل رفع شد و در نسخه‌ی ۳.۸.۲ منتشر شد. لطفاً بررسی و در صورت رضایت تیکت را تأیید کنید." }),
      ],
    ),
    mk(
      {
        id: "MSH-1029",
        title: "چطور برای جانشینِ دوران مرخصی نقش زمان‌دار تعریف کنم؟",
        description: "کارشناس مالی هلدینگ دو ماه مرخصی است و می‌خواهم دسترسی‌هایش موقتاً به همکار دیگری داده شود.",
        type: "سؤال",
        module: "نقش و دسترسی",
        priority: "کم",
        severity: "جزئی",
        status: "closed",
        reporterId: "u2",
        reporterName: "حسین دهقان",
        reporterScopeId: "h-sina-food",
        assigneeId: "v1",
        firstResponseAt: ago(118),
        resolvedAt: ago(117),
        rating: { score: 5, comment: "پاسخ دقیق و سریع بود.", at: ago(110) },
        context: ctx("/dashboard/access", "نقش و دسترسی من", "بنیاد مستضعفان › هلدینگ صنایع غذایی سینا", "مدیر محتوا، مدیر هلدینگ", 120),
      },
      120,
      [
        st(118, "new", "triage", V1),
        ev(118, "comment", V1, "vendor", { text: "در «تنظیمات سامانه ← نقش‌ها» هنگام تخصیص نقش، «اعتبار از» و «اعتبار تا» را پر کنید؛ پس از تاریخ پایان، نقش خودکار بی‌اثر می‌شود و در تاریخچه ثبت می‌گردد." }),
        st(117, "triage", "resolved", V1),
        st(110, "resolved", "closed", "حسین دهقان", "reporter", "پاسخ را تأیید کردم."),
        ev(110, "rating", "حسین دهقان", "reporter", { to: "5", text: "پاسخ دقیق و سریع بود." }),
      ],
    ),
    mk(
      {
        id: "MSH-1030",
        title: "پیشنهاد: ارسال خلاصه‌ی هفتگی وظایف به ایمیل شخصی",
        description: "خوب است هر شنبه فهرست وظایف عقب‌افتاده و این هفته به ایمیل شخصی‌ام هم بیاید.",
        type: "پیشنهاد",
        module: "فعالیت و وظایف",
        priority: "کم",
        severity: "جزئی",
        status: "rejected",
        reporterId: "u3",
        reporterName: "محمد سعیدی‌کیا",
        reporterScopeId: "c-behnoush",
        assigneeId: "v1",
        firstResponseAt: ago(90),
        resolvedAt: ago(89),
        context: ctx("/dashboard/my-work", "فعالیت‌ها و وظایف", "بنیاد مستضعفان › هلدینگ صنایع غذایی سینا › بهنوش ایران", "کاربر عادی", 96, "Chrome 127 · Android", "۳۹۰×۸۴۴ (صفحه‌نمایش ۳۹۰×۸۴۴)"),
      },
      96,
      [
        st(90, "new", "triage", V1),
        st(89, "triage", "rejected", V1, "vendor", "طبق سیاست امنیتی بنیاد، ارسال داده‌ی کاری به ایمیل‌های شخصی مجاز نیست؛ خلاصه‌ی هفتگی در صندوق اعلان‌های سامانه ارسال می‌شود."),
      ],
    ),
    mk(
      {
        id: "MSH-1031",
        title: "ثبت ساعت کاری در روز تعطیل رسمی خطا می‌دهد",
        description: "برای بازدید اضطراری روز تعطیل ساعت کاری ثبت کردم اما پیام «تاریخ نامعتبر» آمد.",
        type: "خطا",
        module: "گزارش فعالیت و زمان کاری",
        priority: "متوسط",
        severity: "متوسط",
        status: "closed",
        reporterId: "u9",
        reporterName: "دکتر نگین فرهمند",
        reporterScopeId: "c-energy-sina",
        assigneeId: "v3",
        firstResponseAt: ago(262),
        resolvedAt: ago(240),
        fixedIn: "۳.۸.۱",
        rating: { score: 4, at: ago(230) },
        labels: ["زمان کاری"],
        context: ctx("/dashboard/activity", "گزارش فعالیت‌های من", "بنیاد مستضعفان › هلدینگ برق و انرژی صبا › انرژی گستر سینا", "کاربر عادی", 268, "Chrome 126 · Windows", "۱۳۶۶×۶۵۰ (صفحه‌نمایش ۱۳۶۶×۷۶۸)", "۳.۸.۰"),
      },
      268,
      [
        st(262, "new", "triage", V4),
        ev(262, "comment", V4, "vendor", { text: "بازتولید شد؛ اعتبارسنجی تاریخ، روزهای تعطیل را رد می‌کند." }),
        ev(261, "assign", V1, "vendor", { to: V3 }),
        st(250, "triage", "in-progress", V3),
        ev(240.5, "release", V3, "vendor", { to: "۳.۸.۱" }),
        st(240, "in-progress", "resolved", V3, "vendor", "در نسخه‌ی ۳.۸.۱ رفع شد."),
        st(230, "resolved", "closed", "دکتر نگین فرهمند", "reporter"),
        ev(230, "rating", "دکتر نگین فرهمند", "reporter", { to: "4" }),
      ],
    ),
    mk(
      {
        id: "MSH-1032",
        title: "اعلان «پاسخ به شما» در پرسش و پاسخ نمی‌آید",
        description: "به پرسشم در بخش پرسش و پاسخ دو نفر پاسخ داده‌اند اما اعلانی دریافت نکردم.",
        type: "خطا",
        module: "اعلان‌ها",
        priority: "متوسط",
        severity: "متوسط",
        status: "new",
        reporterId: "u10",
        reporterName: "مهندس پارسا یگانه",
        reporterScopeId: "c-dashtnaz",
        context: ctx("/dashboard/forum/q12", "پرسش و پاسخ", "بنیاد مستضعفان › هلدینگ کشاورزی فردوس پارس › کشت و صنعت دشت ناز ساری", "کاربر عادی", 3, "Chrome 128 · Android", "۴۱۲×۸۹۲ (صفحه‌نمایش ۴۱۲×۸۹۲)"),
      },
      3,
      [],
    ),
    mk(
      {
        id: "MSH-1033",
        title: "بارگذاری فایل بزرگ در مخزن دانش انجام نمی‌شود",
        description: "فایل ۶۰ مگابایتی بارگذاری نمی‌شود.",
        type: "خطا",
        module: "مدیریت دانش",
        priority: "متوسط",
        severity: "متوسط",
        status: "closed",
        reporterId: "u12",
        reporterName: "دکتر یاسمن روشن",
        reporterScopeId: "h-sina-food",
        assigneeId: "v3",
        firstResponseAt: ago(20),
        resolvedAt: ago(20),
        links: [{ id: "MSH-1024", kind: "duplicate-of" }],
        context: ctx("/dashboard/knowledge?tab=bank", "مدیریت دانش", "بنیاد مستضعفان › هلدینگ صنایع غذایی سینا", "کاربر عادی، کارشناس مالی هلدینگ", 22, "Firefox 130 · Windows"),
      },
      22,
      [
        ev(20, "link", V1, "vendor", { to: "MSH-1024", text: "تکراریِ" }),
        st(20, "new", "closed", V1, "vendor", "این مورد تکراریِ MSH-1024 است و پیگیری در همان تیکت انجام می‌شود."),
      ],
    ),
    mk(
      {
        id: "MSH-1034",
        title: "ورود یکپارچه (SSO) با حساب سازمانی بنیاد",
        description: "کاربران می‌خواهند با همان حساب سازمانی (Active Directory) وارد موتوشاب شوند تا رمز جداگانه نداشته باشند.",
        type: "درخواست قابلیت",
        module: "ورود و حساب کاربری",
        priority: "زیاد",
        severity: "متوسط",
        status: "in-progress",
        reporterId: "u1",
        reporterName: "پایگاه اطلاع‌رسانی بنیاد",
        reporterScopeId: "sys",
        assigneeId: "v3",
        firstResponseAt: ago(140),
        fixedIn: "۳.۹.۰",
        labels: ["امنیت", "یکپارچه‌سازی"],
        context: ctx("/dashboard/settings?section=security", "تنظیمات سامانه", "بنیاد مستضعفان", "مدیر سامانه", 144),
      },
      144,
      [
        st(140, "new", "triage", V1),
        ev(140, "comment", V1, "vendor", { text: "درخواست ثبت شد. برای پیاده‌سازی، مشخصات سرور LDAP/ADFS سازمان را از واحد فناوری اطلاعات دریافت می‌کنیم." }),
        ev(100, "comment", "پایگاه اطلاع‌رسانی بنیاد", "reporter", { text: "مشخصات ADFS به ایمیل سرپرست پشتیبانی ارسال شد.", files: ["adfs-metadata.xml"] }),
        ev(100, "attachment", "پایگاه اطلاع‌رسانی بنیاد", "reporter", { files: ["adfs-metadata.xml"] }),
        ev(99, "assign", V1, "vendor", { to: V3 }),
        ev(98, "release", V1, "vendor", { to: "۳.۹.۰" }),
        st(98, "triage", "in-progress", V3),
        ev(97, "note", V3, "vendor", { internal: true, text: "OIDC از طریق ADFS — گواهی امضا تا پایان ماه منقضی می‌شود؛ قبل از استقرار تمدید شود." }),
        ev(26, "priority", V1, "vendor", { from: "متوسط", to: "زیاد", text: "به درخواست مدیریت بنیاد" }),
      ],
    ),
    mk(
      {
        id: "MSH-1035",
        title: "جستجوی فارسی با «ی» عربی نتیجه‌ای نمی‌دهد",
        description: "عبارتی را که از فایل Word کپی می‌کنم در جستجو نتیجه ندارد؛ ظاهراً «ي» و «ك» عربی است.",
        type: "خطا",
        module: "جستجو",
        priority: "متوسط",
        severity: "متوسط",
        status: "closed",
        reporterId: "u7",
        reporterName: "دکتر مهسا نیک‌اندیش",
        reporterScopeId: "c-ferdows-agri",
        assigneeId: "v3",
        firstResponseAt: ago(300),
        resolvedAt: ago(232),
        fixedIn: "۳.۸.۱",
        rating: { score: 3, comment: "رفع شد ولی کمی طول کشید.", at: ago(220) },
        labels: ["جستجو", "فارسی"],
        context: ctx("/dashboard/search?q=کیت", "جستجو", "بنیاد مستضعفان › هلدینگ کشاورزی فردوس پارس › موسسه تحقیقات کشاورزی بنیاد", "مدیر گروه", 310, "Chrome 126 · Windows", "۱۹۲۰×۹۴۰ (صفحه‌نمایش ۱۹۲۰×۱۰۸۰)", "۳.۸.۰"),
      },
      310,
      [
        st(300, "new", "triage", V4),
        ev(299, "assign", V1, "vendor", { to: V3 }),
        st(290, "triage", "in-progress", V3),
        ev(233, "release", V3, "vendor", { to: "۳.۸.۱" }),
        st(232, "in-progress", "resolved", V3),
        st(220, "resolved", "closed", "دکتر مهسا نیک‌اندیش", "reporter"),
        ev(220, "rating", "دکتر مهسا نیک‌اندیش", "reporter", { to: "3", text: "رفع شد ولی کمی طول کشید." }),
      ],
    ),
    mk(
      {
        id: "MSH-1036",
        title: "پیشرفت هلدینگ در داشبورد با جمع پروژه‌های شرکت‌ها هم‌خوانی ندارد",
        description: "داشبورد هلدینگ پیشرفت را ۶۲٪ نشان می‌دهد اما میانگین وزنی پروژه‌های شرکت‌ها حدود ۴۸٪ است.",
        type: "خطا",
        module: "داشبورد",
        priority: "زیاد",
        severity: "متوسط",
        status: "triage",
        reporterId: "u4",
        reporterName: "وحید خاوئی",
        reporterScopeId: "h-ferdows",
        assigneeId: "v4",
        firstResponseAt: ago(28),
        labels: ["گزارش"],
        context: ctx("/dashboard", "داشبورد", "بنیاد مستضعفان › هلدینگ کشاورزی فردوس پارس", "مدیر هلدینگ، مدیر پروژه", 30),
      },
      30,
      [
        st(28, "new", "triage", V1),
        ev(28, "assign", V1, "vendor", { to: V4 }),
        ev(27.8, "comment", V4, "vendor", { text: "در حال بررسی فرمول وزن‌دهی پروژه‌ها هستیم." }),
        ev(27, "comment", "وحید خاوئی", "reporter", { text: "پروژه‌های بسته‌شده هم در محاسبه آمده‌اند؟" }),
      ],
    ),
    mk(
      {
        id: "MSH-1037",
        title: "میان‌بر صفحه‌کلید جستجوی سراسری در مرورگر Firefox کار نمی‌کند",
        description: "کلید Ctrl+K در Firefox به‌جای جستجوی سامانه، نوار جستجوی مرورگر را باز می‌کند.",
        type: "خطا",
        module: "جستجو",
        priority: "کم",
        severity: "جزئی",
        status: "resolved",
        reporterId: "u1",
        reporterName: "پایگاه اطلاع‌رسانی بنیاد",
        reporterScopeId: "sys",
        assigneeId: "v2",
        firstResponseAt: ago(47),
        resolvedAt: ago(2),
        fixedIn: "۳.۸.۲",
        context: ctx("/dashboard/my-work", "فعالیت‌ها و وظایف", "بنیاد مستضعفان", "مدیر سامانه", 48, "Firefox 130 · Linux"),
      },
      48,
      [
        st(47, "new", "triage", V1),
        ev(47, "assign", V1, "vendor", { to: V2 }),
        st(20, "triage", "in-progress", V2),
        ev(2.1, "release", V2, "vendor", { to: "۳.۸.۲" }),
        st(2, "in-progress", "resolved", V2, "vendor"),
        ev(2, "comment", V2, "vendor", { text: "میان‌بر جایگزین «/» اضافه شد و Ctrl+K در Firefox هم پیش از مرورگر دریافت می‌شود. لطفاً بررسی و تأیید کنید." }),
      ],
    ),
  ];
}
